# Generated by Django 6.0.3 on 2026-04-06 14:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('theme_config', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('slug', models.SlugField()),
                ('public_feed_url', models.URLField()),
                ('subscriber_feed_url', models.URLField()),
                ('required_patreon_tier_id', models.TextField(blank=True, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='pod_manager.network')),
            ],
            options={
                'unique_together': {('network', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='UserMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pod_manager.network')),
                ('selected_podcasts', models.ManyToManyField(to='pod_manager.podcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.TextField()),
                ('title', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('audio_url_public', models.URLField()),
                ('audio_url_subscriber', models.URLField()),
                ('raw_description', models.TextField()),
                ('clean_description', models.TextField(blank=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='pod_manager.podcast')),
            ],
            options={
                'indexes': [models.Index(fields=['podcast', '-pub_date'], name='pod_manager_podcast_8b8ce0_idx')],
                'unique_together': {('podcast', 'guid')},
            },
        ),
    ]
