# Generated by Django 6.0.3 on 2026-04-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='global_footer_private',
            field=models.TextField(blank=True, help_text='Appended to all private feeds in this network.'),
        ),
        migrations.AddField(
            model_name='network',
            name='global_footer_public',
            field=models.TextField(blank=True, help_text='Appended to all public feeds in this network.'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='show_footer_private',
            field=models.TextField(blank=True, help_text='Appended above the global private footer.'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='show_footer_public',
            field=models.TextField(blank=True, help_text='Appended above the global public footer.'),
        ),
    ]
