# Generated by Django 6.0.3 on 2026-04-06 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0002_network_global_footer_private_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatreonTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'In Association With'", max_length=100)),
                ('minimum_cents', models.IntegerField(help_text='e.g., 600 for $6.00')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='pod_manager.network')),
            ],
            options={
                'ordering': ['minimum_cents'],
            },
        ),
    ]
