# Generated by Django 6.0.3 on 2026-04-06 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0003_patreontier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='required_patreon_tier_id',
        ),
        migrations.AddField(
            model_name='podcast',
            name='required_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pod_manager.patreontier'),
        ),
    ]
