# Generated by Django 6.0.3 on 2026-04-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0004_remove_podcast_required_patreon_tier_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patreontier',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Automatically assign to new podcasts.'),
        ),
    ]
