# Generated by Django 6.0.3 on 2026-04-06 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0005_patreontier_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatronProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patreon_id', models.CharField(max_length=50, unique=True)),
                ('pledge_amount_cents', models.IntegerField(default=0)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patron_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
