# Generated by Django 6.0.3 on 2026-04-06 19:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0006_patronprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronprofile',
            name='feed_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
