# Generated by Django 6.0.3 on 2026-04-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0008_alter_patronprofile_feed_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='feed_cache_minutes',
            field=models.IntegerField(default=15, help_text='How long to cache feeds in minutes.'),
        ),
    ]
