# Generated by Django 6.0.3 on 2026-04-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0009_network_feed_cache_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='image_url',
            field=models.URLField(blank=True, help_text='Automatically populated from the RSS feed.'),
        ),
    ]
