# Generated by Django 6.0.3 on 2026-04-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0010_podcast_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='duration',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
