# Generated by Django 6.0.3 on 2026-04-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0011_episode_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='default_image_url',
            field=models.URLField(blank=True, help_text='Fallback logo for RSS feeds'),
        ),
        migrations.AddField(
            model_name='network',
            name='ignored_title_tags',
            field=models.TextField(blank=True, help_text="Comma-separated list of tags to strip during import (e.g., '(ad-free), premium')"),
        ),
        migrations.AddField(
            model_name='network',
            name='patreon_campaign_id',
            field=models.CharField(blank=True, help_text='The numeric ID of the Patreon Campaign', max_length=100),
        ),
        migrations.AddField(
            model_name='network',
            name='website_url',
            field=models.URLField(blank=True, help_text='e.g., https://yournetwork.com'),
        ),
    ]
