# Generated by Django 6.0.3 on 2026-04-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0012_network_default_image_url_network_ignored_title_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='description_cut_triggers',
            field=models.TextField(blank=True, help_text="Comma-separated phrases to trigger paragraph deletion (e.g., 'ad choices, leave a review')"),
        ),
    ]
