# Generated by Django 6.0.3 on 2026-04-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0013_network_description_cut_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermix',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional custom artwork'),
        ),
        migrations.AddField(
            model_name='usermix',
            name='name',
            field=models.CharField(default='My Custom Mix', max_length=200),
        ),
    ]
