# Generated by Django 6.0.3 on 2026-04-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0014_usermix_image_url_usermix_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermix',
            name='image_upload',
            field=models.ImageField(blank=True, help_text='Uploaded artwork', null=True, upload_to='mix_covers/'),
        ),
    ]
