# Generated by Django 6.0.3 on 2026-04-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0015_usermix_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermix',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional custom artwork URL'),
        ),
    ]
