# Generated by Django 6.0.3 on 2026-04-08 20:56

import pod_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0016_alter_usermix_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermix',
            name='image_upload',
            field=models.ImageField(blank=True, help_text='Uploaded artwork', null=True, upload_to=pod_manager.models.mix_cover_path),
        ),
    ]
