# Generated by Django 6.0.3 on 2026-04-08 21:08

import pod_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0017_alter_usermix_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermix',
            name='image_upload',
            field=models.ImageField(blank=True, help_text='Uploaded artwork', null=True, storage=pod_manager.models.OverwriteStorage(), upload_to=pod_manager.models.mix_cover_path),
        ),
    ]
