# Generated by Django 6.0.3 on 2026-04-09 15:22

import pod_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0018_alter_usermix_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='theme_config',
            field=models.JSONField(blank=True, default=pod_manager.models.default_theme_config),
        ),
    ]
