# Generated by Django 6.0.3 on 2026-04-09 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0019_alter_network_theme_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='owners',
            field=models.ManyToManyField(blank=True, help_text="Users who have admin access to this network's settings.", related_name='owned_networks', to=settings.AUTH_USER_MODEL),
        ),
    ]
