# Generated by Django 6.0.3 on 2026-04-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0020_network_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronprofile',
            name='active_pledges',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
