# Generated by Django 6.0.3 on 2026-04-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0021_patronprofile_active_pledges'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='url_bluesky',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='network',
            name='url_patreon',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='network',
            name='url_twitch',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='network',
            name='url_twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='network',
            name='url_youtube',
            field=models.URLField(blank=True),
        ),
    ]
