# Generated by Django 6.0.3 on 2026-04-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0022_network_url_bluesky_network_url_patreon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='match_reason',
            field=models.CharField(blank=True, help_text='Audit trail for how the private audio was matched during ingestion.', max_length=100),
        ),
    ]
