# Generated by Django 6.0.3 on 2026-04-10 15:56

import pod_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0023_episode_match_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='custom_domain',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='network',
            name='patreon_creator_access_token',
            field=pod_manager.models.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='patreon_creator_refresh_token',
            field=pod_manager.models.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='patreon_sync_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
