# Generated by Django 6.0.3 on 2026-04-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0024_network_custom_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='network',
            name='ingester_module',
            field=models.CharField(default='default', help_text="The script in pod_manager/ingesters/ to use. Default is 'default'.", max_length=50),
        ),
    ]
