# Generated by Django 6.0.3 on 2026-04-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0025_episode_tags_network_ingester_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
