# Generated by Django 6.0.3 on 2026-04-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0026_episode_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='chapters_private',
            field=models.JSONField(blank=True, help_text='Podcast Index Namespace Chapters for private feed', null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='chapters_public',
            field=models.JSONField(blank=True, help_text='Podcast Index Namespace Chapters for public feed', null=True),
        ),
    ]
