# Generated by Django 6.0.3 on 2026-04-16 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0027_episode_chapters_private_episode_chapters_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronprofile',
            name='last_active',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
