# Generated by Django 6.0.3 on 2026-04-16 21:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0028_patronprofile_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat monthly platform fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='network',
            name='per_user_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost per active 30-day patron', max_digits=10),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_user_count', models.IntegerField(default=0)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pdf_file', models.FileField(upload_to='invoices/')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='pod_manager.network')),
            ],
        ),
    ]
