# Generated by Django 6.0.3 on 2026-04-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0029_network_base_cost_network_per_user_cost_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio_url_public',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='episode',
            name='audio_url_subscriber',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='episode',
            name='link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image_url',
            field=models.URLField(blank=True, help_text='Automatically populated from the RSS feed.', max_length=2000),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='public_feed_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='subscriber_feed_url',
            field=models.URLField(max_length=2000),
        ),
    ]
