# Generated by Django 6.0.3 on 2026-04-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0030_alter_episode_audio_url_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio_url_public',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='audio_url_subscriber',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='public_feed_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='subscriber_feed_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
