# Generated by Django 6.0.3 on 2026-04-21 15:33

import django.db.models.deletion
import pod_manager.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0031_alter_episode_audio_url_public_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('image_url', models.URLField(blank=True, help_text='Optional custom artwork URL', max_length=2000)),
                ('image_upload', models.ImageField(blank=True, help_text='Uploaded artwork', null=True, storage=pod_manager.models.OverwriteStorage(), upload_to=pod_manager.models.mix_cover_path)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mixes', to='pod_manager.network')),
                ('required_tier', models.ForeignKey(blank=True, help_text='If set, the entire feed requires this tier to access.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pod_manager.patreontier')),
                ('selected_podcasts', models.ManyToManyField(to='pod_manager.podcast')),
            ],
            options={
                'unique_together': {('network', 'slug')},
            },
        ),
    ]
