# Generated by Django 6.0.3 on 2026-04-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0032_networkmix'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='guid_private',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='guid_public',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='is_metadata_locked',
            field=models.BooleanField(default=False, help_text='If checked, future feed ingests will ONLY update the audio URLs. Title, Description, and Dates will not be overwritten.'),
        ),
    ]
