# Generated by Django 6.0.3 on 2026-04-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0034_copy_guid_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['podcast', 'guid_public'], name='pod_manager_podcast_7fd799_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['podcast', 'guid_private'], name='pod_manager_podcast_7957b7_idx'),
        ),
        migrations.RemoveField(
            model_name='episode',
            name='guid',
        ),
    ]
