# Generated by Django 6.0.3 on 2026-04-23 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0035_alter_episode_options_alter_episode_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patronprofile',
            name='current_obsession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obsessed_fans', to='pod_manager.podcast'),
        ),
        migrations.AddField(
            model_name='patronprofile',
            name='edits_chapters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patronprofile',
            name='edits_descriptions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patronprofile',
            name='edits_rejected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patronprofile',
            name='edits_tags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patronprofile',
            name='first_responder_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patronprofile',
            name='last_playback_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patronprofile',
            name='streak_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patronprofile',
            name='streak_weeks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patronprofile',
            name='total_hours_accessed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='patronprofile',
            name='total_playback_hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patronprofile',
            name='trust_score',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='EpisodeEditSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_data', models.JSONField(default=dict)),
                ('original_data', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('is_first_responder', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_suggestions', to='pod_manager.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_edits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rss_hits', models.IntegerField(default=0)),
                ('playback_hits', models.IntegerField(default=0)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='pod_manager.network')),
                ('podcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='pod_manager.podcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'network'], name='pod_manager_date_f893ec_idx'), models.Index(fields=['user', 'date'], name='pod_manager_user_id_00de61_idx')],
                'unique_together': {('user', 'network', 'podcast', 'date')},
            },
        ),
    ]
