# Generated by Django 6.0.3 on 2026-04-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0036_patronprofile_current_obsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronprofile',
            name='patreon_join_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
