# Generated by Django 6.0.3 on 2026-04-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0037_patronprofile_patreon_join_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patronprofile',
            name='patreon_join_date',
        ),
        migrations.AddField(
            model_name='patronprofile',
            name='patreon_join_dates',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
