# Generated by Django 6.0.3 on 2026-04-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0038_remove_patronprofile_patreon_join_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='auto_approve_trust_threshold',
            field=models.IntegerField(default=100, help_text='Users with a trust score equal to or above this number bypass the review inbox. (Set to 101 to disable auto-approve).'),
        ),
    ]
