# Generated by Django 6.0.3 on 2026-04-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0039_network_auto_approve_trust_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='auto_approve_trust_threshold',
            field=models.IntegerField(default=80, help_text='Users with a trust score equal to or above this number bypass the review inbox. (Set to 101 to disable auto-approve).'),
        ),
        migrations.AlterField(
            model_name='patronprofile',
            name='trust_score',
            field=models.IntegerField(default=0),
        ),
    ]
