# Generated by Django 6.0.3 on 2026-04-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0040_alter_network_auto_approve_trust_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronprofile',
            name='last_play_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
