# Generated by Django 6.0.3 on 2026-04-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0041_patronprofile_last_play_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronprofile',
            name='discord_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patronprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
