# Generated by Django 6.0.3 on 2026-04-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0042_patronprofile_discord_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='patreon_campaign_created_at',
            field=models.DateTimeField(blank=True, help_text='The date the creator launched their Patreon campaign.', null=True),
        ),
    ]
