# Generated by Django 6.0.3 on 2026-04-24 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0043_network_patreon_campaign_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patreon_join_date', models.DateTimeField(blank=True, null=True)),
                ('patreon_pledge_cents', models.IntegerField(default=0)),
                ('is_active_patron', models.BooleanField(default=False)),
                ('trust_score', models.IntegerField(default=100)),
                ('total_playback_hits', models.IntegerField(default=0)),
                ('total_hours_accessed', models.FloatField(default=0.0)),
                ('streak_days', models.IntegerField(default=0)),
                ('streak_weeks', models.IntegerField(default=0)),
                ('last_playback_date', models.DateField(blank=True, null=True)),
                ('last_play_week', models.IntegerField(blank=True, null=True)),
                ('edits_chapters', models.IntegerField(default=0)),
                ('edits_tags', models.IntegerField(default=0)),
                ('edits_descriptions', models.IntegerField(default=0)),
                ('first_responder_count', models.IntegerField(default=0)),
                ('current_obsession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pod_manager.podcast')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='pod_manager.network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'network')},
            },
        ),
    ]
