# Generated by Django 6.0.3 on 2026-04-24 17:59

from django.db import migrations

def copy_gamification_to_membership(apps, schema_editor):
    PatronProfile = apps.get_model('pod_manager', 'PatronProfile')
    NetworkMembership = apps.get_model('pod_manager', 'NetworkMembership')
    Network = apps.get_model('pod_manager', 'Network')

    # Get the Bald Move network (or the first available network if the name differs slightly)
    target_network = Network.objects.filter(name__icontains="Bald Move").first()
    if not target_network:
        target_network = Network.objects.first()
        
    if not target_network:
        return # Abort if no networks exist

    for profile in PatronProfile.objects.all():
        # Create a membership record mapping all old stats to the target network
        NetworkMembership.objects.create(
            user=profile.user,
            network=target_network,
            trust_score=profile.trust_score,
            total_playback_hits=profile.total_playback_hits,
            total_hours_accessed=profile.total_hours_accessed,
            streak_days=profile.streak_days,
            streak_weeks=profile.streak_weeks,
            last_playback_date=profile.last_playback_date,
            last_play_week=profile.last_play_week,
            current_obsession=profile.current_obsession,
            edits_chapters=profile.edits_chapters,
            edits_tags=profile.edits_tags,
            edits_descriptions=profile.edits_descriptions,
            first_responder_count=profile.first_responder_count
        )

class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0044_networkmembership'),
    ]

    operations = [
        migrations.RunPython(copy_gamification_to_membership),
    ]
