# Generated by Django 6.0.3 on 2026-04-24 18:05

from django.db import migrations
from django.utils import timezone

def patch_missing_patreon_data(apps, schema_editor):
    PatronProfile = apps.get_model('pod_manager', 'PatronProfile')
    NetworkMembership = apps.get_model('pod_manager', 'NetworkMembership')

    for membership in NetworkMembership.objects.all():
        try:
            profile = PatronProfile.objects.get(user=membership.user)
            campaign_id = str(membership.network.patreon_campaign_id)
            
            # 1. Extract Pledges & Active Status
            cents = 0
            if profile.active_pledges:
                cents = profile.active_pledges.get(campaign_id, 0)
                # Fallback for test data: if the campaign ID doesn't match perfectly, 
                # just grab the highest pledge they have so your test users stay active.
                if cents == 0 and len(profile.active_pledges) > 0:
                    cents = max(profile.active_pledges.values())
            
            membership.patreon_pledge_cents = cents
            membership.is_active_patron = (cents > 0)

            # 2. Extract Account Vintage (Join Date)
            if profile.patreon_join_dates:
                date_str = profile.patreon_join_dates.get(campaign_id)
                # Test data fallback
                if not date_str and len(profile.patreon_join_dates) > 0:
                    date_str = list(profile.patreon_join_dates.values())[0]
                    
                if date_str:
                    try:
                        membership.patreon_join_date = timezone.datetime.fromisoformat(date_str.replace('Z', '+00:00'))
                    except Exception:
                        pass
                        
            membership.save()
        except PatronProfile.DoesNotExist:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0045_migrate_stats_to_baldmove'),
    ]

    operations = [
        migrations.RunPython(patch_missing_patreon_data),
    ]
