# Generated by Django 6.0.3 on 2026-04-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0046_patch_patreon_membership_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patronprofile',
            name='active_pledges',
        ),
        migrations.RemoveField(
            model_name='patronprofile',
            name='current_obsession',
        ),
        migrations.RemoveField(
            model_name='patronprofile',
            name='edits_chapters',
        ),
        migrations.RemoveField(
            model_name='patronprofile',
            name='edits_descriptions',
        ),
        migrations.RemoveField(
            model_name='patronprofile',
            name='edits_rejected',
        ),
        migrations.RemoveField(
            model_name='patronprofile',
            name='edits_tags',
        ),
        migrations.RemoveField(
            model_name='patronprofile',
            name='first_responder_count',
        ),
        migrations.RemoveField(
            model_name='patronprofile',
            name='last_play_week',
        ),
        migrations.RemoveField(
            model_name='patronprofile',
            name='last_playback_date',
        ),
        migrations.RemoveField(
            model_name='patronprofile',
            name='patreon_join_dates',
        ),
        migrations.RemoveField(
            model_name='patronprofile',
            name='pledge_amount_cents',
        ),
        migrations.RemoveField(
            model_name='patronprofile',
            name='streak_days',
        ),
        migrations.RemoveField(
            model_name='patronprofile',
            name='streak_weeks',
        ),
        migrations.RemoveField(
            model_name='patronprofile',
            name='total_hours_accessed',
        ),
        migrations.RemoveField(
            model_name='patronprofile',
            name='total_playback_hits',
        ),
        migrations.RemoveField(
            model_name='patronprofile',
            name='trust_score',
        ),
    ]
