# Generated by Django 6.0.3 on 2026-04-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0047_remove_patronprofile_active_pledges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patreontier',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
