# Generated by Django 6.0.3 on 2026-04-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0048_patreontier_checkout_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='banner_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='discord_server_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='one_liner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='patreon_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
