# Generated by Django 6.0.3 on 2026-04-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0049_network_banner_image_url_network_discord_server_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='contact_email',
            field=models.EmailField(default='hosts@example.com', help_text='The official contact email displayed in RSS feeds for podcatcher verification.', max_length=254),
        ),
    ]
