# Generated by Django 6.0.3 on 2026-04-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0050_network_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='description',
            field=models.TextField(blank=True, help_text='The main description for the podcast feed.', null=True),
        ),
    ]
