# Generated by Django 6.0.3 on 2026-04-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0051_podcast_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedanalytics',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='feedanalytics',
            name='pod_manager_date_f893ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='feedanalytics',
            name='pod_manager_user_id_00de61_idx',
        ),
        migrations.RemoveField(
            model_name='patronprofile',
            name='last_active',
        ),
        migrations.AddField(
            model_name='networkmembership',
            name='last_active_date',
            field=models.DateField(blank=True, db_index=True, help_text="The last date this user interacted with this network's web or RSS properties.", null=True),
        ),
        migrations.DeleteModel(
            name='FeedAnalytics',
        ),
    ]
