# Generated by Django 6.0.3 on 2026-04-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0052_alter_feedanalytics_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkmembership',
            name='active_recurly_plans',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patronprofile',
            name='recurly_account_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
