# Generated by Django 6.0.3 on 2026-04-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0053_networkmembership_active_recurly_plans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patreontier',
            name='recurly_plan_code',
            field=models.CharField(blank=True, help_text="The exact 'plan_code' string from Recurly", max_length=255, null=True),
        ),
    ]
