# Generated by Django 6.0.3 on 2026-04-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0054_patreontier_recurly_plan_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkmembership',
            name='edits_title',
            field=models.IntegerField(default=0),
        ),
    ]
