# Generated by Django 6.0.3 on 2026-04-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0055_networkmembership_edits_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmembership',
            name='trust_score',
            field=models.IntegerField(default=0),
        ),
    ]
