# Generated by Django 6.0.3 on 2026-04-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0056_alter_networkmembership_trust_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkmembership',
            name='discord_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
