# Generated by Django 6.0.3 on 2026-04-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0057_networkmembership_discord_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkmembership',
            name='custom_image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='custom_avatars/'),
        ),
        migrations.AddField(
            model_name='networkmembership',
            name='custom_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='networkmembership',
            name='preferred_avatar_source',
            field=models.CharField(choices=[('patreon', 'Patreon'), ('discord', 'Discord'), ('custom', 'Custom')], default='discord', max_length=20),
        ),
    ]
