# Generated by Django 6.0.3 on 2026-04-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0058_networkmembership_custom_image_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmembership',
            name='preferred_avatar_source',
            field=models.CharField(choices=[('patreon', 'Patreon'), ('discord', 'Discord'), ('custom', 'Custom')], default='discord', max_length=20),
        ),
    ]
