# Generated by Django 6.0.3 on 2026-05-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0059_alter_networkmembership_preferred_avatar_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patreontier',
            name='recurly_plan_code',
        ),
        migrations.AddField(
            model_name='patreontier',
            name='recurly_plan_codes',
            field=models.JSONField(blank=True, default=list, help_text='List of Recurly plan codes: ["cbm-monthly", "cbm-yearly"]'),
        ),
    ]
