# Generated by Django 6.0.3 on 2026-05-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0060_remove_patreontier_recurly_plan_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmembership',
            name='preferred_avatar_source',
            field=models.CharField(choices=[('patreon', 'Patreon'), ('discord', 'Discord'), ('gravatar', 'Gravatar'), ('custom', 'Custom')], default='discord', max_length=20),
        ),
    ]
