# Generated by Django 6.0.3 on 2026-05-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0061_alter_networkmembership_preferred_avatar_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronprofile',
            name='active_recurly_plans',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
