# Generated by Django 6.0.3 on 2026-05-01 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0062_patronprofile_active_recurly_plans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkmembership',
            name='active_recurly_plans',
        ),
    ]
