# Generated by Django 6.0.3 on 2026-05-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0063_remove_networkmembership_active_recurly_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patronprofile',
            name='patreon_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
