# Generated by Django 6.0.3 on 2026-05-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0064_alter_patronprofile_patreon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronprofile',
            name='totp_mode',
            field=models.CharField(choices=[('replace', 'Replace email OTP'), ('mfa', 'Require both (MFA)')], default='replace', max_length=10),
        ),
    ]
