# Generated by Django 6.0.3 on 2026-05-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0065_add_totp_mode_to_patron_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('level_no', models.IntegerField(db_index=True)),
                ('logger_name', models.CharField(max_length=200)),
                ('module', models.CharField(max_length=200)),
                ('func_name', models.CharField(max_length=200)),
                ('lineno', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'log entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
