# Generated by Django 6.0.3 on 2026-05-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0068_episode_publish_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
