# Generated by Django 6.0.3 on 2026-06-05 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0070_episode_audio_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('vtt_file', models.CharField(blank=True, max_length=500, null=True)),
                ('json_file', models.CharField(blank=True, max_length=500, null=True)),
                ('srt_file', models.CharField(blank=True, max_length=500, null=True)),
                ('html_file', models.CharField(blank=True, max_length=500, null=True)),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('source_audio_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('whisper_model_used', models.CharField(blank=True, max_length=50)),
                ('retry_count', models.IntegerField(default=0)),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='pod_manager.episode')),
            ],
            options={
                'verbose_name_plural': 'transcripts',
            },
        ),
    ]
