# Generated by Django 6.0.3 on 2026-06-12 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0075_podcast_whisper_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeCrossPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_mode', models.CharField(choices=[('inherit', "Keep episode's own gating (parent podcast tier)"), ('target', "Use the target podcast's tier")], default='inherit', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_publications', to='pod_manager.episode')),
                ('podcast', models.ForeignKey(help_text='Target podcast whose feeds also carry this episode.', on_delete=django.db.models.deletion.CASCADE, related_name='cross_publications_in', to='pod_manager.podcast')),
            ],
            options={
                'indexes': [models.Index(fields=['podcast', 'episode'], name='pod_manager_podcast_278109_idx')],
                'constraints': [models.UniqueConstraint(fields=('episode', 'podcast'), name='uniq_episode_crosspub_target')],
            },
        ),
    ]
