# Generated by Django 6.0.3 on 2026-06-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0076_episodecrosspublication'),
        ('pod_manager', '0077_network_whisper_num_speakers_nullable'),
    ]

    operations = [
    ]
