# Generated by Django 6.0.3 on 2026-06-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0078_merge_20260616_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='worker',
            field=models.CharField(blank=True, help_text='Host/worker that ran the transcription.', max_length=255),
        ),
    ]
