# Generated by Django 6.0.3 on 2026-06-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0079_transcript_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('awaiting_recovery', 'Awaiting Recovery')], db_index=True, default='pending', max_length=20),
        ),
    ]
