# Generated by Django 6.0.3 on 2026-06-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0080_alter_transcript_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='whisper_model',
            field=models.CharField(blank=True, default='medium.en', help_text='Whisper model size: tiny/base/small/medium/large or language-specific (e.g. medium.en). Leave blank to use the system default (WHISPER_DEFAULT_MODEL / WHISPER_MODEL).', max_length=50),
        ),
    ]
