# Generated by Django 6.0.3 on 2026-06-18 15:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0081_alter_network_whisper_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='r2_source_signature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='episode',
            name='r2_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='When the R2 mirror was last written.', null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='r2_url',
            field=models.URLField(blank=True, db_index=True, help_text='Public URL of the mirrored subscriber audio on R2. Presence means a backup exists.', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='force_r2_serve',
            field=models.BooleanField(default=False, help_text="Serve this podcast's audio from the R2 mirror whenever a mirror exists, instead of the original host."),
        ),
        migrations.CreateModel(
            name='R2OrphanedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1024, unique=True)),
                ('orphaned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Retention clock start; cleanup expiry is computed per reason.')),
                ('reason', models.CharField(choices=[('reversion', 'Re-versioned (new content hash)'), ('move_rekey', 'Re-keyed on move (byte-identical copy at new key)'), ('reconciliation', 'Found unreferenced by reconciliation sweep'), ('manual', 'Manually recorded')], default='manual', max_length=20)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pod_manager.episode')),
            ],
        ),
    ]
