# Generated by Django 6.0.3 on 2026-06-25 21:11

import pod_manager.models
import pod_manager.services.r2_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0082_episode_r2_source_signature_episode_r2_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkmembership',
            name='image_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkmix',
            name='image_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermix',
            name='image_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='networkmembership',
            name='custom_image_upload',
            field=models.ImageField(blank=True, null=True, storage=pod_manager.services.r2_storage.select_media_storage, upload_to=pod_manager.models.avatar_upload_path),
        ),
        migrations.AlterField(
            model_name='networkmix',
            name='image_upload',
            field=models.ImageField(blank=True, help_text='Uploaded artwork', null=True, storage=pod_manager.services.r2_storage.select_media_storage, upload_to=pod_manager.models.mix_cover_path),
        ),
        migrations.AlterField(
            model_name='usermix',
            name='image_upload',
            field=models.ImageField(blank=True, help_text='Uploaded artwork', null=True, storage=pod_manager.services.r2_storage.select_media_storage, upload_to=pod_manager.models.mix_cover_path),
        ),
    ]
