# Generated by Django 6.0.3 on 2026-06-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0083_networkmembership_image_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
