# Generated by Django 6.0.3 on 2026-06-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0086_commandrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodeeditsuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('rolled_back', 'Rolled Back'), ('superseded', 'Superseded')], default='pending', max_length=20),
        ),
    ]
