# Generated by Django 6.0.3 on 2026-06-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0087_alter_episodeeditsuggestion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodeeditsuggestion',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkmembership',
            name='edits_sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkmembership',
            name='edits_speakers',
            field=models.IntegerField(default=0),
        ),
    ]
