# Generated by Django 6.0.3 on 2026-06-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0088_episodeeditsuggestion_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodeeditsuggestion',
            name='counter_deltas',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
