# Generated by Django 6.0.3 on 2026-07-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0090_commandrun_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='explicit',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
