# Generated by Django 6.0.3 on 2026-07-09 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0091_episode_explicit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='podcast_pinned_at',
            field=models.DateTimeField(blank=True, help_text="Set whenever an episode's podcast is manually changed (single or bulk move). GUID-based ingest auto-migration skips pinned episodes so they aren't moved back to a prior feed. Never blocks manual moves.", null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='podcast_pinned_by',
            field=models.ForeignKey(blank=True, help_text='Who performed the most recent manual move (audit trail).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
