# Generated by Django 6.0.3 on 2026-07-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0092_episode_podcast_pinned_at_episode_podcast_pinned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='is_low_priority',
            field=models.BooleanField(default=False, help_text='Episodes that arrive here first via GUID match will be auto-migrated to a normal-priority feed that later ingests the same episode. Also polled slightly after normal feeds.'),
        ),
    ]
