# Generated by Django 6.0.3 on 2026-07-09 21:47

import django.db.models.deletion
import pod_manager.models
import pod_manager.services.r2_storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0093_podcast_is_low_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotFoundEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image_upload', models.ImageField(storage=pod_manager.services.r2_storage.select_media_storage, upload_to=pod_manager.models.notfound_image_path)),
                ('image_version', models.IntegerField(default=0)),
                ('caption', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notfound_entries', to='pod_manager.network')),
            ],
        ),
    ]
