# Generated by Django 6.0.3 on 2026-07-09 23:11

import pod_manager.models
import pod_manager.services.r2_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0094_notfoundentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='custom_font_family',
            field=models.CharField(blank=True, help_text="Font name declared in the generated @font-face rule (e.g. 'Brand Sans').", max_length=100),
        ),
        migrations.AddField(
            model_name='network',
            name='custom_font_upload',
            field=models.FileField(blank=True, help_text="Self-hosted .woff2 file for this network's theme font.", null=True, storage=pod_manager.services.r2_storage.select_media_storage, upload_to=pod_manager.models.network_font_path),
        ),
    ]
