# Generated by Django 6.0.3 on 2026-07-09 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0095_network_custom_font'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('season_number', models.IntegerField(blank=True, null=True)),
                ('episode_number', models.IntegerField(blank=True, null=True)),
                ('episode_type', models.CharField(blank=True, max_length=50)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('external_link', models.URLField(blank=True, help_text='Where to go for a non-episode entry (e.g. a Live Watch link).')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('episode', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_entry', to='pod_manager.episode')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='pod_manager.network')),
                ('podcast', models.ForeignKey(blank=True, help_text='Leave blank for a non-episode entry (e.g. a Live Watch).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_entries', to='pod_manager.podcast')),
            ],
        ),
    ]
