# Generated by Django 6.0.3 on 2026-07-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0096_calendarentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='custom_font_version',
            field=models.IntegerField(default=0, help_text='Bumped on every font upload — cache-busts the stable fonts/<slug>.woff2 key, which the CDN serves with a 1-year immutable cache.'),
        ),
    ]
