# Generated by Django 6.0.3 on 2026-07-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0097_network_custom_font_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkmembership',
            name='seen_notfound_entries',
            field=models.ManyToManyField(blank=True, related_name='seen_by_members', to='pod_manager.notfoundentry'),
        ),
    ]
