# Generated by Django 6.0.3 on 2026-07-10 23:09

import pod_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0098_networkmembership_seen_notfound_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='allow_public_transcripts',
            field=models.BooleanField(default=True, help_text='Serve transcripts (and the podcast:transcript feed tag) to listeners without premium access to this podcast. Turn off for feeds where the private audio contains content never released publicly (e.g. extended spoiler sections) — the single transcript is always generated from the private audio.'),
        ),
        # Two-step so existing rows migrate as NULL (legacy deterministic key) and
        # are NOT backfilled with a single shared token. AddField applies the
        # field's default to every existing row — a callable default is evaluated
        # ONCE, so all rows would get the same token and their keyed key would miss
        # the objects still living at the legacy key. Add as NULL first, then set
        # the callable default (a state/DB-default change only — it never rewrites
        # existing row data), so only new INSERTs are born keyed (D4).
        migrations.AddField(
            model_name='transcript',
            name='r2_key_token',
            field=models.CharField(blank=True, default=None, help_text="Random suffix mixed into the R2 object keys so they can't be derived from the episode id. Null = legacy deterministic key (pre-rekey). Set at creation for new transcripts; backfilled by rekey_transcripts.", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='r2_key_token',
            field=models.CharField(blank=True, default=pod_manager.models.new_transcript_token, help_text="Random suffix mixed into the R2 object keys so they can't be derived from the episode id. Null = legacy deterministic key (pre-rekey). Set at creation for new transcripts; backfilled by rekey_transcripts.", max_length=32, null=True),
        ),
    ]
