# Generated by Django 6.0.3 on 2026-07-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0099_podcast_allow_public_transcripts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodecrosspublication',
            name='auto_created',
            field=models.BooleanField(default=False, help_text='True if this link was generated by feed-level auto cross-publish (teardown removes only these).'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='auto_crosspublish_access_mode',
            field=models.CharField(choices=[('inherit', "Keep episode's own gating (parent podcast tier)"), ('target', "Use the target podcast's tier")], default='inherit', help_text="Tier gating for this feed's auto cross-published episodes inside their destinations. INHERIT = keep this feed's tier; TARGET = adopt the destination feed's tier.", max_length=10),
        ),
        migrations.AddField(
            model_name='podcast',
            name='auto_crosspublish_targets',
            field=models.ManyToManyField(blank=True, help_text='Every episode in THIS feed is automatically cross-published into each selected destination feed.', related_name='auto_crosspublish_sources', to='pod_manager.podcast'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text="Hide this feed from the Your Feeds subscription directory. The feed's own RSS URL keeps working; existing subscribers are unaffected."),
        ),
    ]
