# Generated by Django 6.0.3 on 2026-07-14 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0100_episodecrosspublication_auto_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSchedulePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, max_length=32)),
                ('message_id', models.CharField(max_length=32, unique=True)),
                ('guild_id', models.CharField(blank=True, max_length=32)),
                ('window_kind', models.CharField(default='week', max_length=8)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField(db_index=True, help_text='Exclusive window edge; also the live-update expiry.')),
                ('subtitle', models.CharField(blank=True, help_text='Frozen human window label shown on the embed.', max_length=200)),
                ('created_by_discord_id', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_schedule_posts', to='pod_manager.network')),
            ],
        ),
    ]
