# Generated by Django 6.0.3 on 2026-07-17 02:04

import pod_manager.models
import pod_manager.services.r2_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0101_liveschedulepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='default_image_upload',
            field=models.ImageField(blank=True, help_text='Uploaded fallback logo for RSS feeds and mixes', null=True, storage=pod_manager.services.r2_storage.select_media_storage, upload_to=pod_manager.models.network_default_image_path),
        ),
        migrations.AddField(
            model_name='network',
            name='default_image_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='network',
            name='default_image_url',
            field=models.URLField(blank=True, help_text='Legacy fallback logo URL (superseded by default_image_upload)'),
        ),
    ]
