# Generated by Django 6.0.3 on 2026-07-17 03:47

import pod_manager.models
import pod_manager.services.r2_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0102_network_default_image_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='logo_upload',
            field=models.ImageField(blank=True, help_text='Uploaded network logo, rendered in the navbar', null=True, storage=pod_manager.services.r2_storage.select_media_storage, upload_to=pod_manager.models.network_logo_path),
        ),
        migrations.AddField(
            model_name='network',
            name='logo_version',
            field=models.IntegerField(default=0),
        ),
    ]
