# Generated by Django 6.0.3 on 2026-07-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0103_network_logo_upload_network_logo_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarentry',
            name='created_from_episode',
            field=models.BooleanField(default=False),
        ),
    ]
