# Generated by Django 6.0.3 on 2026-07-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0104_calendarentry_created_from_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarentry',
            name='placeholder_notes',
            field=models.TextField(blank=True, help_text='Public-facing teaser notes shown until the episode publishes (teaser mode).'),
        ),
        migrations.AddField(
            model_name='calendarentry',
            name='placeholder_title',
            field=models.CharField(blank=True, help_text='Public-facing teaser title shown until the episode publishes (teaser mode).', max_length=255),
        ),
        migrations.AddField(
            model_name='calendarentry',
            name='prepublish_visibility',
            field=models.CharField(choices=[('actual', 'Show actual info'), ('teaser', 'Show teaser'), ('hidden', 'Hidden until publish')], default='actual', max_length=10),
        ),
    ]
