# Generated by Django 6.0.3 on 2026-07-17 22:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0105_calendarentry_placeholder_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeMatchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_guid', models.TextField()),
                ('priv_guid', models.TextField()),
                ('detected_reason', models.CharField(help_text="'ambiguous_guid_divergence' from live ingest, 'backfill_duplicate_guid' from the backfill command.", max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_suggestions', to='pod_manager.network')),
                ('private_episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_suggestions_as_private', to='pod_manager.episode')),
                ('public_episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_suggestions_as_public', to='pod_manager.episode')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pod_manager.podcast')),
                ('target_podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pod_manager.podcast')),
            ],
            options={
                'indexes': [models.Index(fields=['network', 'status'], name='pod_manager_network_690dbf_idx'), models.Index(fields=['last_seen_at'], name='pod_manager_last_se_80db7b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('public_episode', 'private_episode'), name='uniq_pending_match_suggestion_pair')],
            },
        ),
    ]
