# Generated by Django 6.0.3 on 2026-07-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0106_episodematchsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r2orphanedobject',
            name='reason',
            field=models.CharField(choices=[('reversion', 'Re-versioned (new content hash)'), ('move_rekey', 'Re-keyed on move (byte-identical copy at new key)'), ('reconciliation', 'Found unreferenced by reconciliation sweep'), ('manual', 'Manually recorded'), ('merge_transcript', 'Transcript superseded by episode merge')], default='manual', max_length=20),
        ),
    ]
