# Generated by Django 6.0.3 on 2026-10-01 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0107_alter_r2orphanedobject_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(condition=models.Q(('guid_private__contains', '?p=vecto-')), fields=('guid_private',), name='uniq_generated_guid_private'),
        ),
    ]
