# Generated by Django 6.0.3 on 2026-10-01 21:23

import pod_manager.models
from django.db import migrations, models


def backfill_stems(apps, schema_editor):
    """Give every existing transcript the stem its objects ALREADY live under — the
    exact historical derivation (inlined so later code changes can't alter it):
        untokened -> transcripts/{id // 1000}/{id}
        tokened   -> transcripts/{id // 1000}/{id}.{token}
    No object moves; this only records where they are."""
    Transcript = apps.get_model('pod_manager', 'Transcript')
    batch = []
    for t in Transcript.objects.filter(r2_key_stem__isnull=True).only(
            'id', 'episode_id', 'r2_key_token').iterator(chunk_size=500):
        tail = f"{t.episode_id}.{t.r2_key_token}" if t.r2_key_token else str(t.episode_id)
        t.r2_key_stem = f"transcripts/{t.episode_id // 1000}/{tail}"
        batch.append(t)
        if len(batch) >= 500:
            Transcript.objects.bulk_update(batch, ['r2_key_stem'])
            batch = []
    if batch:
        Transcript.objects.bulk_update(batch, ['r2_key_stem'])


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0108_unique_generated_guid_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='transcript_key_pattern',
            field=models.CharField(blank=True, default='', help_text="R2 key stem for new transcripts. Blank = transcripts/{bucket}/{episode_id}.{token}. Must start with 'transcripts/' and contain {token}. Placeholders: {bucket} (episode id // 1000), {episode_id}, {token}, {network_slug}, {podcast_slug}. Changing it only affects transcripts created afterwards; run `manage.py rekey_transcripts --normalize --apply` to move existing ones.", max_length=200, validators=[pod_manager.models.validate_transcript_key_pattern]),
        ),
        migrations.AddField(
            model_name='transcript',
            name='r2_key_stem',
            field=models.CharField(blank=True, db_index=True, help_text="Where this transcript's R2 objects live ({stem}.{ext}). Managed by the system; change it with `rekey_transcripts`, which moves the objects too.", max_length=300, null=True),
        ),
        migrations.RunPython(backfill_stems, migrations.RunPython.noop),
    ]
