# Generated by Django 6.0.3 on 2026-10-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0109_transcript_key_stem'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='header_stamp',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
