# Generated by Django 6.0.3 on 2026-10-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_manager', '0110_transcript_header_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='explicit_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podcast',
            name='explicit',
            field=models.BooleanField(blank=True, help_text="Override this feed's content rating. Blank = follow the source feed.", null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='feed_explicit',
            field=models.BooleanField(blank=True, editable=False, help_text='The rating the source feed declares (captured on ingest).', null=True),
        ),
    ]
