"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv

# Load environment variables from the .env file
load_dotenv()

# Patreon OAuth Credentials
PATREON_CLIENT_ID = os.getenv("PATREON_CLIENT_ID")
PATREON_CLIENT_SECRET = os.getenv("PATREON_CLIENT_SECRET")
PATREON_REDIRECT_URI = os.getenv("PATREON_REDIRECT_URI")
PATREON_WEBHOOK_SECRET = os.getenv("PATREON_WEBHOOK_SECRET")

# Discord Credentials
DISCORD_BOT_TOKEN = os.getenv("DISCORD_BOT_TOKEN")

# Whisper ASR / Transcription (onerahmet/openai-whisper-asr-webservice)
# IDE: set WHISPER_URL in .env to point at the whisper container on Unraid
# DEV: same Unraid URL (or http://host.docker.internal:9000 from inside Docker)
# PROD: defaults to http://whisper:9000 once Phase 11 adds whisper to the stack
WHISPER_URL               = os.getenv("WHISPER_URL", "http://whisper:9000")
WHISPER_ENABLED           = os.getenv("WHISPER_ENABLED", "True") == "True"
WHISPER_MODEL             = os.getenv("WHISPER_MODEL", "medium.en")
# Per-worker model controls (set in each worker container's environment):
#   WHISPER_FORCE_MODEL   — hard pin: this worker transcribes EVERYTHING with this
#       model, overriding even an explicit per-call model. Use to keep a GPU box on
#       one model (e.g. 3060=large-v3) and avoid the multi-model VRAM blowup.
#   WHISPER_DEFAULT_MODEL — soft default: used only when no model is passed and no
#       podcast/network override exists. An explicit per-call model still wins.
# Empty = fall through to the global WHISPER_MODEL.
WHISPER_FORCE_MODEL       = os.getenv("WHISPER_FORCE_MODEL", "")
WHISPER_DEFAULT_MODEL     = os.getenv("WHISPER_DEFAULT_MODEL", "")
WHISPER_LANGUAGE          = os.getenv("WHISPER_LANGUAGE", "en")
WHISPER_TIMEOUT           = int(os.getenv("WHISPER_TIMEOUT", "5400"))
WHISPER_KEEP_SOURCE_AUDIO = os.getenv("WHISPER_KEEP_SOURCE_AUDIO", "False") == "True"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Traefik Integration
TRAEFIK_API_TOKEN = os.environ.get('TRAEFIK_API_TOKEN', 'fallback-dev-token')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
RAW_DEBUG = os.getenv('DEBUG', 'False')

# Check if we are running in the local IDE environment
IS_IDE = (RAW_DEBUG == 'IDE')

# Django's internal DEBUG needs to be a boolean, so it's True if 'True' OR 'IDE'
DEBUG = (RAW_DEBUG in ['True', 'IDE'])

# TOTP Issuer
OTP_TOTP_ISSUER = 'Vecto'

# ==========================================
# ALLOWED HOSTS (Dynamic Multi-Tenant)
# ==========================================
class DynamicTenantHosts(list):
    def __contains__(self, host):
        # 1. Global Wildcard Bypass
        if '*' in self:
            return True

        clean_host = host.split(':')[0].lower()

        # 2. Check explicitly defined .env hosts
        for base in self:
            base = base.lower()
            if base.startswith('.') and clean_host.endswith(base): 
                return True
            if clean_host == base: 
                return True

        # 3. Check database for dynamic client domains
        try:
            from pod_manager.models import Network
            return Network.objects.filter(custom_domain__iexact=clean_host).exists()
        except Exception:
            return False
# ==========================================
# CSRF ORIGINS (Linked to Allowed Hosts)
# ==========================================
class DynamicTenantCSRF(list):
    def __init__(self, allowed_hosts_instance):
        self.allowed_hosts = allowed_hosts_instance

    def __contains__(self, origin):
        # The origin looks like 'https://vecto.joshtheblack.com'
        try:
            # Strip the scheme (http:// or https://) to isolate the domain
            host = origin.split('://')[1].lower()
            # Feed the domain directly into our Allowed Hosts checker!
            return host in self.allowed_hosts
        except IndexError:
            return False
            
    def __iter__(self):
        # Django's CSRF middleware tries to iterate over this list to check
        # for strict wildcards if __contains__ fails. We just return empty.
        return iter([])
    
# Grab raw strings from .env
env_hosts_string = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1')
base_hosts_list = [h.strip() for h in env_hosts_string.split(',') if h.strip()]

# Assign dynamic host validator
ALLOWED_HOSTS = DynamicTenantHosts(base_hosts_list)
CSRF_TRUSTED_ORIGINS = DynamicTenantCSRF(ALLOWED_HOSTS)

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'cryptography',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_otp',
    'django_otp.plugins.otp_totp',
    "anymail",
    'pod_manager',
]

CRYPTOGRAPHY_KEY = os.environ.get('DJANGO_CRYPTOGRAPHY_KEY', 'generate-a-secure-random-string-here')

ANYMAIL = {
    "MAILGUN_API_KEY": os.environ.get('MAILGUN_API_KEY'),
    "MAILGUN_SENDER_DOMAIN": os.environ.get('MAILGUN_SENDER_DOMAIN'),
}
EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
DEFAULT_FROM_EMAIL = f"login@{os.environ.get('MAILGUN_SENDER_DOMAIN')}"
RECURLY_API_KEY = os.environ.get('RECURLY_API_KEY')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'pod_manager.middleware.ImpersonationMiddleware',
    'pod_manager.middleware.RequestUserLogMiddleware',  # after Impersonation — captures effective user
    'pod_manager.middleware.NetworkMiddleware',
    'pod_manager.middleware.BillingPresenceMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pod_manager.context_processors.current_network',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# HYBRID DATABASE ROUTING
IS_TEST = 'test' in sys.argv

if IS_IDE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 20,
                'init_command': 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;',
            }
        }
    }
elif IS_TEST:
    # Bypass PgBouncer for tests — CREATE DATABASE requires a direct connection
    # and a user with CREATEDB privilege (set TEST_DB_USER/TEST_DB_PASSWORD in .env)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'vecto'),
            'USER': os.getenv('TEST_DB_USER', 'vecto_test'),
            'PASSWORD': os.getenv('TEST_DB_PASSWORD', ''),
            'HOST': os.getenv('POSTGRES_HOST_DIRECT', 'db'),
            'PORT': '5432',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'vecto'),
            'USER': os.getenv('POSTGRES_USER', 'vecto_user'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'vecto_pass'),

            # Route through the Bouncer
            'HOST': os.getenv('POSTGRES_HOST', 'pgbouncer'),
            'PORT': os.getenv('POSTGRES_PORT', '6432'),

            # Connection Pooling
            'CONN_MAX_AGE': 60,
            'CONN_HEALTH_CHECKS': True,
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static & Media
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "pod_manager" / "static",
]
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# ==========================================
# MEDIA SETTINGS (For User Uploads)
# ==========================================
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# AUTHENTICATION ROUTING
LOGIN_URL = 'patreon_login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# ==========================================
# LOGGING CONFIGURATION
# ==========================================
# Use LOG_LEVEL=DEBUG in your .env for verbose output, default to INFO for production
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()
LOG_RETENTION_DAYS = int(os.getenv("LOG_RETENTION_DAYS", "30"))

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} [{module}.{funcName}:{lineno}] - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'filters': {
        # Keeps console output at the configured LOG_LEVEL even though the
        # pod_manager logger itself runs at DEBUG so the DB handler can receive
        # everything and apply its own live-togglable level gate.
        'console_level': {
            '()': 'pod_manager.log_handler.MinLevelFilter',
            'min_level': LOG_LEVEL,
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            # StreamHandler defaults to stderr, which IDE run windows often
            # hide or buffer separately — log to stdout so app logs appear
            # alongside runserver output.
            'stream': 'ext://sys.stdout',
            'formatter': 'verbose',
            'filters': ['console_level'],
        },
        'database': {
            'class': 'pod_manager.log_handler.DatabaseLogHandler',
            'level': 'DEBUG',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'), # Keep Django internal logs quieter
            'propagate': False,
        },
        'pod_manager': {
            'handlers': ['console', 'database'],
            # Always DEBUG so every record reaches the handlers; each handler
            # applies its own level gate independently.
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# HYBRID CACHE & CELERY ROUTING
if IS_IDE:
    # Use Local Memory Cache
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }
    # Force Celery to bypass Redis and run everything instantly in the same terminal
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
    # DatabaseLogHandler writes a LogEntry to SQLite from a background daemon
    # thread on every log call. SQLite takes only one writer, so under WAL-mode
    # locking those background writes compete with the request thread's own
    # writes and surface as "database is locked" (lock-upgrade conflicts return
    # BUSY immediately, bypassing the busy_timeout) — e.g. the multi-feed
    # publish flow, which emits several log lines per request. Route the
    # pod_manager logger to console in the IDE env; Postgres in prod takes
    # concurrent writers and keeps the full DB log viewer.
    LOGGING['loggers']['pod_manager']['handlers'] = ['console']

    # Disable transcription signal in tests — individual test classes opt-in via override_settings
    if IS_TEST:
        WHISPER_ENABLED = False
else:
    # Use Redis Cache & Full Celery Worker Pipeline
    RAW_REDIS_URL = os.getenv("REDIS_URL")
    REDIS_URL = RAW_REDIS_URL.strip('"\'') if RAW_REDIS_URL else "redis://redis:6379/0"
    
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
    CELERY_BROKER_URL = REDIS_URL
    CELERY_RESULT_BACKEND = REDIS_URL

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Redis has no native unacked-message tracking: Celery redelivers any message
# unacked for longer than visibility_timeout (default 3600s). Transcription
# tasks run 1-2+ hours, so the default silently duplicates them mid-run.
# Must stay comfortably above the longest task runtime incl. queue wait.
#
# queue_order_strategy='priority' enables Redis soft-priority: Celery keeps a
# separate per-priority sublist per queue and the worker drains lower numbers
# first. On the Redis transport LOWER = sooner (0 is highest), opposite of
# RabbitMQ. Priority only reorders *waiting* messages — it can't preempt the
# transcription already running on the concurrency=1 worker.
#
# priority_steps defines the discrete priority buckets. We carve two bands so a
# worker draining BOTH transcription queues always finishes heavy work first:
#   heavy  (transcription_heavy): 0=high 1=default 2=low
#   normal (transcription):       7=high 8=default 9=low
# A worker's BRPOP scans buckets low→high, so any heavy job (0-2) outranks any
# normal job (7-9) regardless of in-band level. 3-6 are reserved for future
# bands. route_transcription() in services/transcription.py assigns these.
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 43200,  # 12 h
    'queue_order_strategy': 'priority',
    'priority_steps': [0, 1, 2, 7, 8, 9],
}
CELERY_TASK_QUEUE_MAX_PRIORITY = 10
CELERY_TASK_DEFAULT_PRIORITY = 5

# Don't reserve a backlog of unacked messages per worker process — with
# multi-hour tasks, prefetched messages exceed the visibility timeout while
# waiting and get redelivered as duplicates.
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

CELERY_BEAT_SCHEDULE = {
    'sync-bot-avatar-hourly': {
        'task': 'pod_manager.tasks.task_sync_bot_avatar',
        'schedule': 3600,  # seconds
    },
    'prune-log-entries-daily': {
        'task': 'pod_manager.tasks.task_prune_logs',
        'schedule': 86400,  # seconds (24 h)
    },
    'publish-scheduled-episodes': {
        'task': 'pod_manager.tasks.task_publish_scheduled_episodes',
        'schedule': 60,  # every minute
    },
}

# Django Celery Beat for Scheduled Tasks
INSTALLED_APPS += ['django_celery_beat']