"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from the .env file
load_dotenv()

# Patreon OAuth Credentials
PATREON_CLIENT_ID = os.getenv("PATREON_CLIENT_ID")
PATREON_CLIENT_SECRET = os.getenv("PATREON_CLIENT_SECRET")
PATREON_REDIRECT_URI = os.getenv("PATREON_REDIRECT_URI")
PATREON_WEBHOOK_SECRET = os.getenv("PATREON_WEBHOOK_SECRET")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Traefik Integration
TRAEFIK_API_TOKEN = os.environ.get('TRAEFIK_API_TOKEN', 'fallback-dev-token')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
RAW_DEBUG = os.getenv('DEBUG', 'False')

# Check if we are running in the local IDE environment
IS_IDE = (RAW_DEBUG == 'IDE')

# Django's internal DEBUG needs to be a boolean, so it's True if 'True' OR 'IDE'
DEBUG = (RAW_DEBUG in ['True', 'IDE'])

# ==========================================
# ALLOWED HOSTS (Dynamic Multi-Tenant)
# ==========================================
class DynamicTenantHosts(list):
    def __contains__(self, host):
        # 1. Global Wildcard Bypass
        if '*' in self:
            return True

        clean_host = host.split(':')[0].lower()

        # 2. Check explicitly defined .env hosts
        for base in self:
            base = base.lower()
            if base.startswith('.') and clean_host.endswith(base): 
                return True
            if clean_host == base: 
                return True

        # 3. Check database for dynamic client domains
        try:
            from pod_manager.models import Network
            return Network.objects.filter(custom_domain__iexact=clean_host).exists()
        except Exception:
            return False
# ==========================================
# CSRF ORIGINS (Linked to Allowed Hosts)
# ==========================================
class DynamicTenantCSRF(list):
    def __init__(self, allowed_hosts_instance):
        self.allowed_hosts = allowed_hosts_instance

    def __contains__(self, origin):
        # The origin looks like 'https://vecto.joshtheblack.com'
        try:
            # Strip the scheme (http:// or https://) to isolate the domain
            host = origin.split('://')[1].lower()
            # Feed the domain directly into our Allowed Hosts checker!
            return host in self.allowed_hosts
        except IndexError:
            return False
            
    def __iter__(self):
        # Django's CSRF middleware tries to iterate over this list to check
        # for strict wildcards if __contains__ fails. We just return empty.
        return iter([])
    
# Grab raw strings from .env
env_hosts_string = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1')
base_hosts_list = [h.strip() for h in env_hosts_string.split(',') if h.strip()]

# Assign dynamic host validator
ALLOWED_HOSTS = DynamicTenantHosts(base_hosts_list)
CSRF_TRUSTED_ORIGINS = DynamicTenantCSRF(ALLOWED_HOSTS)

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'cryptography',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pod_manager',
]

CRYPTOGRAPHY_KEY = os.environ.get('DJANGO_CRYPTOGRAPHY_KEY', 'generate-a-secure-random-string-here')



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'pod_manager.middleware.ImpersonationMiddleware',
    'pod_manager.middleware.NetworkMiddleware', 
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pod_manager.context_processors.current_network',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# HYBRID DATABASE ROUTING
if IS_IDE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 20,
                'init_command': 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;',
            }
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'vecto'),
            'USER': os.getenv('POSTGRES_USER', 'vecto_user'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'vecto_pass'),
            
            # 1. Route through the Bouncer
            'HOST': os.getenv('POSTGRES_HOST', 'pgbouncer'),
            'PORT': os.getenv('POSTGRES_PORT', '6432'),
            
            # 2. Activate Connection Pooling
            'CONN_MAX_AGE': 60,         # Keep connections alive for 60 seconds
            'CONN_HEALTH_CHECKS': True, # Ensure Django drops dead connections gracefully
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static & Media
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "pod_manager" / "static",
]
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# ==========================================
# MEDIA SETTINGS (For User Uploads)
# ==========================================
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# AUTHENTICATION ROUTING
LOGIN_URL = 'patreon_login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# ==========================================
# LOGGING CONFIGURATION
# ==========================================
# Use LOG_LEVEL=DEBUG in your .env for verbose output, default to INFO for production
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} [{module}.{funcName}:{lineno}] - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'), # Keep Django internal logs quieter
            'propagate': False,
        },
        'pod_manager': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}

# HYBRID CACHE & CELERY ROUTING
if IS_IDE:
    # Use Local Memory Cache
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }
    # Force Celery to bypass Redis and run everything instantly in the same terminal
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
else:
    # Use Redis Cache & Full Celery Worker Pipeline
    RAW_REDIS_URL = os.getenv("REDIS_URL")
    REDIS_URL = RAW_REDIS_URL.strip('"\'') if RAW_REDIS_URL else "redis://redis:6379/0"
    
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
    CELERY_BROKER_URL = REDIS_URL
    CELERY_RESULT_BACKEND = REDIS_URL

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Django Celery Beat for Scheduled Tasks
INSTALLED_APPS += ['django_celery_beat']