"""Private-GUID links: `https://<network host>/?p=<value>` -> the episode page.

Imported private GUIDs are already URLs of this shape (WordPress permalinks such
as https://baldmove.com/?p=110339). The home view resolves a `?p=` on `/` through
resolve_private_guid and redirects to the episode, so those GUIDs are followable.

Episodes created by the publish flow get a *generated* private GUID in the same
shape. Its value is an opaque random token, deliberately not derived from the
episode id: ids change when an episode is deleted and re-added or merged, and a
token that was never the id can't be mistaken for (or collide with) a WordPress
numeric post id. The token carries GENERATED_PREFIX so the Merge Desk can tell a
generated GUID from one that came from a real private feed.

Resolution is host-agnostic on purpose (only the `p` value is matched), so a
network changing its custom domain doesn't break existing GUIDs, and an imported
GUID whose host isn't the Vecto domain still resolves.
"""
import logging
import secrets
from urllib.parse import parse_qs, urlparse

from django.conf import settings
from django.db import IntegrityError, transaction
from django.db.models import Q

logger = logging.getLogger(__name__)

GENERATED_PREFIX = 'vecto-'
_MAX_VALUE_LEN = 128


def _base_url(network) -> str:
    if network.custom_domain:
        return f"https://{network.custom_domain}".rstrip('/')
    return getattr(settings, 'SITE_URL', 'http://localhost:8000').rstrip('/')


def generated_guid_q(field='guid_private') -> Q:
    """Rows whose private GUID was generated by Vecto (not ingested from a feed)."""
    return Q(**{f'{field}__contains': f'?p={GENERATED_PREFIX}'})


def make_private_guid(network) -> str:
    """A fresh, unused private GUID URL for `network`."""
    from pod_manager.models import Episode
    base = _base_url(network)
    while True:
        guid = f"{base}/?p={GENERATED_PREFIX}{secrets.token_hex(6)}"
        if not Episode.objects.filter(guid_private=guid).exists():
            return guid


def save_with_generated_guid(episode, network, attempts=5):
    """episode.save() that survives losing a race for its generated private GUID.

    make_private_guid checks for an unused GUID, but the check and the INSERT are
    not atomic: two publishes minting at the same instant could pick the same
    token, and the unique constraint (uniq_generated_guid_private) rejects the
    second. Instead of surfacing that as an error — the publisher would lose their
    form — re-mint and try again. Only a conflict on OUR GUID is retried; any other
    integrity error is re-raised untouched."""
    from pod_manager.models import Episode
    for attempt in range(attempts):
        try:
            with transaction.atomic():      # savepoint: a failed INSERT mustn't poison the caller's transaction
                episode.save()
            return
        except IntegrityError:
            guid = episode.guid_private
            taken = bool(guid) and Episode.objects.filter(guid_private=guid).exclude(pk=episode.pk).exists()
            if not taken or attempt == attempts - 1:
                raise
            logger.warning("guid_links: generated GUID %s was taken concurrently; re-minting", guid)
            episode.guid_private = make_private_guid(network)


def resolve_private_guid(network, value, host=None, include_unpublished=False):
    """The episode in `network` whose private GUID is a URL carrying `?p=<value>`,
    or None. If several match (two source sites reusing the same post id), the one
    whose GUID host equals `host` wins, then the newest."""
    from pod_manager.models import Episode
    value = (value or '').strip()
    if not value or len(value) > _MAX_VALUE_LEN:
        return None

    qs = (Episode.objects
          .filter(podcast__network=network, guid_private__endswith=f'?p={value}')
          .select_related('podcast')
          .order_by('-pub_date', '-id'))
    if not include_unpublished:
        qs = qs.filter(is_published=True)

    matches = []
    for ep in qs:
        parsed = urlparse(ep.guid_private or '')
        if parse_qs(parsed.query).get('p') == [value]:
            matches.append((ep, parsed.netloc.lower()))
    if not matches:
        return None
    if len(matches) > 1:
        logger.warning("guid_links: ?p=%s matches %d episodes in network %s; "
                       "preferring host/newest", value, len(matches), network.slug)
        host = (host or '').lower().split(':')[0]
        for ep, netloc in matches:
            if host and netloc.split(':')[0] == host:
                return ep
    return matches[0][0]
